[package]
name = "aprs_inet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
nom = "7.1.3"
aprs-parser = "0.4.2"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
regex = "1.11.1"
